### PR TITLE
fix: read resource name as uppercase on Windows

### LINKED ISSUE #28982: deno compile does not work (2.2.11)
Version: Deno 2.2.11

Hello. This comment was written with google translate.

I was studying about a web server that serves static resources with Deno.serve() and executes API functions with file-based routing.

The environment is windows. In deno run, I changed only the command to deno compile and created an .exe file, but it compiles but does not run.

When I lowered the version to 2.2.10, it ran well. I used deno-x86_64-pc-windows-msvc.zip.

deno run --allow-all main.ts
>> possible

deno compile --allow-all main.ts
>> automatically downloads the light version, compiles, but does not run

### PR DESCRIPTION
**Pull request by dsherret**
We write the name as uppercase:

https://github.com/denoland/sui/blob/99065f1fcbe6e64992f3eeeca5626c6cd0a17765/lib.rs#L139

So we need to read it as uppercase. I guess sometimes windows was ok with case insensitivity and sometimes not 🤷

This seems to actually fix https://github.com/denoland/deno/issues/28982 for me.

### CODE REVIEW

File: lib.rs [hunk 1]
```diff
@@ -314,7 +315,7 @@ mod pe {
 
             let resource_size = SizeofResource(current_process_hmod, resource_handle);
             if resource_size == 0 {
-                return Err(std::io::Error::last_os_error());
+                return Ok(Some(&[]));
```
Comment (dsherret) [inline lib.rs:318]: Noticed this while debugging. I accidentally did this here: https://github.com/denoland/sui/pull/37/files#diff-0544fc952eefa8d170bbd200b75827f5bb58e39b132e7c871c1bc8a9d5e09ce5R317

**Review by littledivy — APPROVED** [review]
certified windows moment
